[package]
name = "rsraw"
version = "0.1.0"
edition = "2021"

[dependencies]
rsraw-sys = { path = "../rsraw-sys" }
chrono = { version = "0.4", features = ["clock", "serde"] }
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
