# copied from https://github.com/tauri-apps/tauri/blob/dev/.github/workflows/test-core.yml

name: Core Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - {
              target: x86_64-pc-windows-gnu,
              os: windows-latest,
              toolchain: 'nightly-2025-01-01',
              cross: false,
              command: 'test'
            }
          - {
              target: x86_64-unknown-linux-gnu,
              os: ubuntu-latest,
              toolchain: 'nightly-2025-01-01',
              cross: false,
              command: 'test'
            }
          - {
              target: aarch64-apple-darwin,
              os: macos-14,
              toolchain: 'nightly-2025-01-01',
              cross: false,
              command: 'test'
            }
          # - {
          #     target: aarch64-apple-ios,
          #     os: macos-latest,
          #     toolchain: 'nightly-2025-01-01',
          #     cross: false,
          #     command: 'build'
          #   }
          - {
              target: aarch64-linux-android,
              os: ubuntu-latest,
              toolchain: 'nightly-2025-01-01',
              cross: true,
              command: 'build'
            }
    
    steps:
      - uses: actions/checkout@v4
      - name: Install MinGW
        if: contains(matrix.platform.target, 'windows-gnu')
        run: |
          choco install mingw -y
      - name: install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.platform.toolchain }}
          targets: ${{ matrix.platform.target }}
      - name: Disable MSVC
        if: contains(matrix.platform.target, 'windows-gnu')
        run: |
          rustup default ${{ matrix.platform.toolchain }}-${{ matrix.platform.target }}
          rustup toolchain uninstall ${{ matrix.platform.toolchain }}-x86_64-pc-windows-msvc
          rustup target uninstall x86_64-pc-windows-msvc
          rm rust-toolchain.toml
      - name: install Linux dependencies
        if: contains(matrix.platform.target, 'unknown-linux')
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.1 libxdo-dev libayatana-appindicator3-dev
      - uses: Swatinem/rust-cache@v2
      - name: test
        if: ${{ !matrix.platform.cross }}
        run: cargo ${{ matrix.platform.command }} --target ${{ matrix.platform.target }} --all --verbose
      - name: test (using cross)
        if: ${{ matrix.platform.cross }}
        run: |
          cargo install cross --git https://github.com/cross-rs/cross --rev ac4c11cedc97cd7c27faed36e55377a90e6ed618 --locked
          cross ${{ matrix.platform.command }} --target ${{ matrix.platform.target }} --all --verbose
